import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

// Logo paths for each language
const logoMap = {
    en: '/assets/logo-en.svg',
    hi: '/assets/logo-hi.svg',
    bn: '/assets/logo-bn.svg',
    mr: '/assets/logo-mr.svg',
    ta: '/assets/logo-ta.svg',
    te: '/assets/logo-te.svg',
    gu: '/assets/logo-gu.svg',
    kn: '/assets/logo-kn.svg',
    ml: '/assets/logo-ml.svg',
    pa: '/assets/logo-pa.svg',
    or: '/assets/logo-or.svg',
    as: '/assets/logo-as.svg',
    ur: '/assets/logo-ur.svg',
    sa: '/assets/logo-sa.svg',
    mai: '/assets/logo-mai.svg',
    ks: '/assets/logo-ks.svg',
    kok: '/assets/logo-kok.svg',
    sd: '/assets/logo-sd.svg',
    mni: '/assets/logo-mni.svg',
    ne: '/assets/logo-ne.svg',
    doi: '/assets/logo-doi.svg',
    brx: '/assets/logo-brx.svg',
    sat: '/assets/logo-sat.svg',
    bho: '/assets/logo-bho.svg',
    raj: '/assets/logo-raj.svg',
    hne: '/assets/logo-hne.svg',
    bgc: '/assets/logo-bgc.svg',
    mag: '/assets/logo-mag.svg',
    tcy: '/assets/logo-tcy.svg',
    kha: '/assets/logo-kha.svg',
    grt: '/assets/logo-grt.svg',
    lus: '/assets/logo-lus.svg',
    trp: '/assets/logo-trp.svg'
};

// Translation dictionary keyed by ISO-ish language codes -> copy deck
const translations = {
    en: {
        appName: "Swasthya-Mitra",
        findDoctorsTitle: "Find Doctors",
        findDoctorsSubtitle: "Browse available doctors and their clinics",
        doctorName: "Doctor Name",
        doctorSpecialization: "Specialization",
        doctorClinic: "Clinic/Hospital",
        login: "Login",
        register: "Register",
        getStarted: "Get Started",
        dashboard: "Dashboard",
        patientsQueue: "Patients in Queue",
        avgWaitTime: "Avg. Wait Time",
        bookAppointment: "Book Appointment",
        welcome: "Welcome",
        emergencyMode: "Emergency Mode",
        stopEmergency: "Stop Emergency Mode",
        triggerEmergency: "Trigger Emergency",
        goodMorning: "Good Morning",
        upcoming: "Upcoming",
        healthRecords: "Health Records",
        dietPlan: "Diet Plan",
        heroTitle: "Making Clinic Visits",
        heroTitleHighlight: "Smarter",
        heroTitleEnd: ", Smoother, and Stress-Free",
        heroSubtitle: "Swasthya-Mitra handles everything from patient queue management to AI wait-time prediction. Your clinic's digital assistant that never sleeps.",
        aiWaitTime: "AI Wait-Time Prediction",
        aiWaitDesc: "Machine learning models predict exactly how long you'll wait.",
        easyBooking: "Easy Booking",
        easyBookingDesc: "Book via website, app, or just a simple phone call.",
        secureRecords: "Secure Health Records",
        secureRecordsDesc: "Upload and view medical reports safely on the cloud.",
        smartQueue: "Smart Queue Management",
        smartQueueDesc: "Real-time token status and estimated waiting time for patients.",
        featuresHeader: "Features Built for You",
        whyChoose: "Why Choose Swasthya-Mitra?",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        patients: "Patients",
        appointments: "Appointments",
        reports: "Reports",
        queue: "Queue",
        search: "Search",
        notifications: "Notifications",
        home: "Home"
    },
    hi: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डॉक्टर खोजें",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर और उनके क्लिनिक देखें",
        doctorName: "डॉक्टर का नाम",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/हॉस्पिटल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "शुरू करें",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार में मरीज",
        avgWaitTime: "औसत प्रतीक्षा समय",
        bookAppointment: "अपॉइंटमेंट बुक करें",
        welcome: "स्वागत है",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोकें",
        triggerEmergency: "आपातकालीन मोड चालू करें",
        goodMorning: "सुप्रभात",
        upcoming: "आगामी",
        healthRecords: "स्वास्थ्य रिकॉर्ड",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक विजिट को बनाएं",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सुगम और तनाव मुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र मरीज कतार प्रबंधन से लेकर एआई प्रतीक्षा समय भविष्यवाणी तक सब कुछ संभालता है। आपके क्लिनिक का डिजिटल सहायक जो कभी नहीं सोता।",
        aiWaitTime: "एआई प्रतीक्षा समय भविष्यवाणी",
        aiWaitDesc: "मशीन लर्निंग मॉडल बताते हैं कि आपको कितनी देर इंतजार करना होगा।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, ऐप या फोन कॉल से बुक करें।",
        secureRecords: "सुरक्षित स्वास्थ्य रिकॉर्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित रूप से अपलोड करें और देखें।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीजों के लिए रीयल-टाइम टोकन स्थिति और अनुमानित प्रतीक्षा समय।",
        featuresHeader: "आपके लिए बनाए गए फीचर",
        whyChoose: "क्यों चुनें स्वास्थ्य-मित्र?",
        profile: "प्रोफ़ाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजें",
        notifications: "सूचनाएं",
        home: "होम"
    },
    bn: {
        appName: "স্বাস্থ্য-মিত্র",
        findDoctorsTitle: "ডাক্তার খুঁজুন",
        findDoctorsSubtitle: "উপলব্ধ ডাক্তার এবং তাদের ক্লিনিক দেখুন",
        doctorName: "ডাক্তারের নাম",
        doctorSpecialization: "বিশেষত্ব",
        doctorClinic: "ক্লিনিক/হাসপাতাল",
        login: "লগ ইন",
        register: "নিবন্ধন",
        getStarted: "শুরু করুন",
        dashboard: "ড্যাশবোর্ড",
        patientsQueue: "সারিতে রোগী",
        avgWaitTime: "গড় অপেক্ষার সময়",
        bookAppointment: "অ্যাপয়েন্টমেন্ট বুক করুন",
        welcome: "স্বাগতম",
        emergencyMode: "জরুরী মোড",
        stopEmergency: "জরুরী মোড বন্ধ করুন",
        triggerEmergency: "জরুরী মোড চালু করুন",
        goodMorning: "সুপ্রভাত",
        upcoming: "আসন্ন",
        healthRecords: "স্বাস্থ্য রেকর্ড",
        dietPlan: "ডায়েট প্ল্যান",
        heroTitle: "ক্লিনিক ভিজিট করুন",
        heroTitleHighlight: "স্মার্ট",
        heroTitleEnd: ", সহজ এবং চাপমুক্ত",
        heroSubtitle: "স্বাস্থ্য-মিত্র রোগীর সারি ব্যবস্থাপনা থেকে এআই অপেক্ষার সময় পূর্বাভাস পর্যন্ত সবকিছু পরিচালনা করে।",
        aiWaitTime: "এআই অপেক্ষার সময় পূর্বাভাস",
        aiWaitDesc: "মেশিন লার্নিং মডেল সঠিকভাবে অপেক্ষার সময় পূর্বাভাস দেয়।",
        easyBooking: "সহজ বুকিং",
        easyBookingDesc: "ওয়েবসাইট, অ্যাপ বা ফোন কলের মাধ্যমে বুক করুন।",
        secureRecords: "সুরক্ষিত স্বাস্থ্য রেকর্ড",
        secureRecordsDesc: "ক্লাউডে মেডিকেল রিপোর্ট নিরাপদে আপলোড এবং দেখুন।",
        smartQueue: "স্মার্ট সারি ব্যবস্থাপনা",
        smartQueueDesc: "রোগীদের জন্য রিয়েল-টাইম টোকেন স্ট্যাটাস এবং আনুমানিক অপেক্ষার সময়।",
        featuresHeader: "আপনার জন্য তৈরি বৈশিষ্ট্য",
        whyChoose: "কেন বেছে নেবেন স্বাস্থ্য-মিত্র?",
        profile: "প্রোফাইল",
        settings: "সেটিংস",
        logout: "লগ আউট",
        patients: "রোগী",
        appointments: "অ্যাপয়েন্টমেন্ট",
        reports: "রিপোর্ট",
        queue: "সারি",
        search: "অনুসন্ধান",
        notifications: "বিজ্ঞপ্তি",
        home: "হোম"
    },
    mr: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डॉक्टर शोधा",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर आणि त्यांचे क्लिनिक पहा",
        doctorName: "डॉक्टरांचे नाव",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/रुग्णालय",
        login: "लॉग इन",
        register: "नोंदणी",
        getStarted: "सुरू करा",
        dashboard: "डॅशबोर्ड",
        patientsQueue: "रांगेत रुग्ण",
        avgWaitTime: "सरासरी प्रतीक्षा वेळ",
        bookAppointment: "अपॉइंटमेंट बुक करा",
        welcome: "स्वागत आहे",
        emergencyMode: "आणीबाणी मोड",
        stopEmergency: "आणीबाणी मोड थांबवा",
        triggerEmergency: "आणीबाणी मोड सुरू करा",
        goodMorning: "शुभ प्रभात",
        upcoming: "आगामी",
        healthRecords: "आरोग्य नोंदी",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक भेटी करा",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सुलभ आणि तणावमुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र रुग्ण रांग व्यवस्थापनापासून एआय प्रतीक्षा वेळ अंदाजापर्यंत सर्वकाही हाताळते।",
        aiWaitTime: "एआय प्रतीक्षा वेळ अंदाज",
        aiWaitDesc: "मशीन लर्निंग मॉडेल तुम्हाला किती वेळ वाट पहावी लागेल हे सांगतात।",
        easyBooking: "सोपी बुकिंग",
        easyBookingDesc: "वेबसाइट, अॅप किंवा फोन कॉलद्वारे बुक करा।",
        secureRecords: "सुरक्षित आरोग्य नोंदी",
        secureRecordsDesc: "क्लाउडवर वैद्यकीय अहवाल सुरक्षितपणे अपलोड करा आणि पहा।",
        smartQueue: "स्मार्ट रांग व्यवस्थापन",
        smartQueueDesc: "रुग्णांसाठी रिअल-टाइम टोकन स्थिती आणि अंदाजे प्रतीक्षा वेळ।",
        featuresHeader: "तुमच्यासाठी तयार केलेली वैशिष्ट्ये",
        whyChoose: "स्वास्थ्य-मित्र का निवडावे?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्ज",
        logout: "लॉग आउट",
        patients: "रुग्ण",
        appointments: "अपॉइंटमेंट",
        reports: "अहवाल",
        queue: "रांग",
        search: "शोधा",
        notifications: "सूचना",
        home: "होम"
    },
    ta: {
        appName: "சுகாதார மித்ரா",
        findDoctorsTitle: "மருத்துவர்களைக் கண்டறியவும்",
        findDoctorsSubtitle: "கிடைக்கக்கூடிய மருத்துவர்கள் மற்றும் அவர்களின் கிளினிக்குகளைப் பார்க்கவும்",
        doctorName: "மருத்துவரின் பெயர்",
        doctorSpecialization: "சிறப்பு",
        doctorClinic: "கிளினிக்/மருத்துவமனை",
        login: "உள்நுழைய",
        register: "பதிவு",
        getStarted: "தொடங்கவும்",
        dashboard: "டாஷ்போர்டு",
        patientsQueue: "வரிசையில் நோயாளிகள்",
        avgWaitTime: "சராசரி காத்திருப்பு நேரம்",
        bookAppointment: "நியமனம் பதிவு",
        welcome: "வரவேற்பு",
        emergencyMode: "அவசர நிலை",
        stopEmergency: "அவசர நிலையை நிறுத்து",
        triggerEmergency: "அவசர நிலையைத் தொடங்கு",
        goodMorning: "காலை வணக்கம்",
        upcoming: "வரவிருக்கும்",
        healthRecords: "சுகாதார பதிவுகள்",
        dietPlan: "உணவு திட்டம்",
        heroTitle: "கிளினிக் வருகைகளை",
        heroTitleHighlight: "புத்திசாலித்தனமாக",
        heroTitleEnd: ", எளிமையாக மற்றும் மன அழுத்தமின்றி",
        heroSubtitle: "சுகாதார மித்ரா நோயாளர் வரிசை மேலாண்மை முதல் AI காத்திருப்பு நேர முன்னறிவிப்பு வரை அனைத்தையும் கையாளுகிறது।",
        aiWaitTime: "AI காத்திருப்பு நேர முன்னறிவிப்பு",
        aiWaitDesc: "இயந்திர கற்றல் மாதிரிகள் நீங்கள் எவ்வளவு நேரம் காத்திருக்க வேண்டும் என்பதை துல்லியமாக கணிக்கின்றன।",
        easyBooking: "எளிய முன்பதிவு",
        easyBookingDesc: "வலைதளம், பயன்பாடு அல்லது எளிய தொலைபேசி அழைப்பு மூலம் முன்பதிவு செய்யுங்கள்।",
        secureRecords: "பாதுகாப்பான சுகாதார பதிவுகள்",
        secureRecordsDesc: "மருத்துவ அறிக்கைகளை கிளவுடில் பாதுகாப்பாக பதிவேற்றவும் பார்க்கவும்।",
        smartQueue: "புத்திசாலி வரிசை மேலாண்மை",
        smartQueueDesc: "நோயாளிகளுக்கு நிகழ்நேர டோக்கன் நிலை மற்றும் மதிப்பிடப்பட்ட காத்திருப்பு நேரம்।",
        featuresHeader: "உங்களுக்காக உருவாக்கப்பட்ட அம்சங்கள்",
        whyChoose: "ஏன் சுகாதார மித்ராவைத் தேர்வு செய்ய வேண்டும்?",
        profile: "சுயவிவரம்",
        settings: "அமைப்புகள்",
        logout: "வெளியேறு",
        patients: "நோயாளிகள்",
        appointments: "நியமனங்கள்",
        reports: "அறிக்கைகள்",
        queue: "வரிசை",
        search: "தேடு",
        notifications: "அறிவிப்புகள்",
        home: "முகப்பு"
    },
    te: {
        appName: "ఆరోగ్య మిత్ర",
        findDoctorsTitle: "వైద్యులను కనుగొనండి",
        findDoctorsSubtitle: "అందుబాటులో ఉన్న వైద్యులు మరియు వారి క్లినిక్‌లను చూడండి",
        doctorName: "వైద్యుడి పేరు",
        doctorSpecialization: "ప్రత్యేకత",
        doctorClinic: "క్లినిక్/ఆసుపత్రి",
        login: "లాగిన్",
        register: "నమోదు",
        getStarted: "ప్రారంభించండి",
        dashboard: "డాష్‌బోర్డ్",
        patientsQueue: "క్యూలో రోగులు",
        avgWaitTime: "సగటు నిరీక్షణ సమయం",
        bookAppointment: "అపాయింట్‌మెంట్ బుక్ చేయండి",
        welcome: "స్వాగతం",
        emergencyMode: "అత్యవసర మోడ్",
        stopEmergency: "అత్యవసర మోడ్ ఆపు",
        triggerEmergency: "అత్యవసర మోడ్ ప్రారంభించు",
        goodMorning: "శుభోదయం",
        upcoming: "రాబోయే",
        healthRecords: "ఆరోగ్య రికార్డులు",
        dietPlan: "డైట్ ప్లాన్",
        heroTitle: "క్లినిక్ సందర్శనలను",
        heroTitleHighlight: "స్మార్ట్‌గా",
        heroTitleEnd: ", సుసజ్జంగా మరియు ఒత్తిడి లేకుండా",
        heroSubtitle: "ఆరోగ్య మిత్ర రోగుల క్యూ నిర్వహణ నుండి AI నిరీక్షణ సమయ అంచనా వరకు అన్నింటినీ నిర్వహిస్తుంది।",
        aiWaitTime: "AI నిరీక్షణ సమయ అంచనా",
        aiWaitDesc: "మెషిన్ లెర్నింగ్ మోడల్స్ మీరు ఎంత సమయం వేచి ఉండాలో ఖచ్చితంగా అంచనా వేస్తాయి।",
        easyBooking: "సులభ బుకింగ్",
        easyBookingDesc: "వెబ్‌సైట్, యాప్ లేదా సాధారణ ఫోన్ కాల్ ద్వారా బుక్ చేయండి।",
        secureRecords: "సురక్షిత ఆరోగ్య రికార్డులు",
        secureRecordsDesc: "మెడికల్ రిపోర్ట్‌లను క్లౌడ్‌లో సురక్షితంగా అప్‌లోడ్ చేయండి మరియు చూడండి।",
        smartQueue: "స్మార్ట్ క్యూ నిర్వహణ",
        smartQueueDesc: "రోగులకు రియల్-టైమ్ టోకెన్ స్థితి మరియు అంచనా వేసిన నిరీక్షణ సమయం।",
        featuresHeader: "మీ కోసం రూపొందించిన ఫీచర్లు",
        whyChoose: "ఆరోగ్య మిత్రను ఎందుకు ఎంచుకోవాలి?",
        profile: "ప్రొఫైల్",
        settings: "సెట్టింగ్స్",
        logout: "లాగ్ అవుట్",
        patients: "రోగులు",
        appointments: "అపాయింట్‌మెంట్‌లు",
        reports: "నివేదికలు",
        queue: "క్యూ",
        search: "వెతకండి",
        notifications: "నోటిఫికేషన్‌లు",
        home: "హోమ్"
    },
    gu: {
        appName: "સ્વાસ્થ્ય મિત્ર",
        findDoctorsTitle: "ડૉક્ટરો શોધો",
        findDoctorsSubtitle: "ઉપલબ્ધ ડૉક્ટરો અને તેમના ક્લિનિક જુઓ",
        doctorName: "ડૉક્ટરનું નામ",
        doctorSpecialization: "વિશેષતા",
        doctorClinic: "ક્લિનિક/હોસ્પિટલ",
        login: "લૉગ ઇન",
        register: "રજીસ્ટર",
        getStarted: "શરૂ કરો",
        dashboard: "ડેશબોર્ડ",
        patientsQueue: "કતારમાં દર્દીઓ",
        avgWaitTime: "સરેરાશ રાહ જોવાનો સમય",
        bookAppointment: "એપોઇન્ટમેન્ટ બુક કરો",
        welcome: "સ્વાગત છે",
        emergencyMode: "ઇમરજન્સી મોડ",
        stopEmergency: "ઇમરજન્સી મોડ બંધ કરો",
        triggerEmergency: "ઇમરજન્સી મોડ શરૂ કરો",
        goodMorning: "સુપ્રભાત",
        upcoming: "આગામી",
        healthRecords: "આરોગ્ય રેકોર્ડ્સ",
        dietPlan: "ડાયેટ પ્લાન",
        heroTitle: "ક્લિનિક મુલાકાતોને બનાવો",
        heroTitleHighlight: "સ્માર્ટ",
        heroTitleEnd: ", સરળ અને તાણમુક્ત",
        heroSubtitle: "સ્વાસ્થ્ય મિત્ર દર્દી કતાર સંચાલનથી લઈને AI રાહ જોવાના સમયની આગાહી સુધી બધું સંભાળે છે।",
        aiWaitTime: "AI રાહ જોવાના સમયની આગાહી",
        aiWaitDesc: "મશીન લર્નિંગ મોડલ તમારે કેટલો સમય રાહ જોવી પડશે તે ચોક્કસ આગાહી કરે છે।",
        easyBooking: "સરળ બુકિંગ",
        easyBookingDesc: "વેબસાઇટ, એપ્લિકેશન અથવા ફોન કૉલ દ્વારા બુક કરો।",
        secureRecords: "સુરક્ષિત આરોગ્ય રેકોર્ડ્સ",
        secureRecordsDesc: "ક્લાઉડ પર મેડિકલ રિપોર્ટ સુરક્ષિત રીતે અપલોડ કરો અને જુઓ।",
        smartQueue: "સ્માર્ટ કતાર સંચાલન",
        smartQueueDesc: "દર્દીઓ માટે રીયલ-ટાઇમ ટોકન સ્થિતિ અને અંદાજિત રાહ જોવાનો સમય।",
        featuresHeader: "તમારા માટે બનાવેલી સુવિધાઓ",
        whyChoose: "શા માટે સ્વાસ્થ્ય મિત્ર પસંદ કરવું?",
        profile: "પ્રોફાઇલ",
        settings: "સેટિંગ્સ",
        logout: "લૉગ આઉટ",
        patients: "દર્દીઓ",
        appointments: "એપોઇન્ટમેન્ટ્સ",
        reports: "અહેવાલો",
        queue: "કતાર",
        search: "શોધો",
        notifications: "સૂચનાઓ",
        home: "હોમ"
    },
    kn: {
        appName: "ಆರೋಗ್ಯ ಮಿತ್ರ",
        findDoctorsTitle: "ವೈದ್ಯರನ್ನು ಹುಡುಕಿ",
        findDoctorsSubtitle: "ಲಭ್ಯವಿರುವ ವೈದ್ಯರು ಮತ್ತು ಅವರ ಕ್ಲಿನಿಕ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        doctorName: "ವೈದ್ಯರ ಹೆಸರು",
        doctorSpecialization: "ವಿಶೇಷತೆ",
        doctorClinic: "ಕ್ಲಿನಿಕ್/ಆಸ್ಪತ್ರೆ",
        login: "ಲಾಗಿನ್",
        register: "ನೋಂದಣಿ",
        getStarted: "ಪ್ರಾರಂಭಿಸಿ",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        patientsQueue: "ಸರತಿಯಲ್ಲಿ ರೋಗಿಗಳು",
        avgWaitTime: "ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ",
        bookAppointment: "ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಕಾಯ್ದಿರಿಸಿ",
        welcome: "ಸ್ವಾಗತ",
        emergencyMode: "ತುರ್ತು ಸ್ಥಿತಿ",
        stopEmergency: "ತುರ್ತು ಸ್ಥಿತಿ ನಿಲ್ಲಿಸಿ",
        triggerEmergency: "ತುರ್ತು ಸ್ಥಿತಿ ಪ್ರಾರಂಭಿಸಿ",
        goodMorning: "ಶುಭೋದಯ",
        upcoming: "ಮುಂಬರುವ",
        healthRecords: "ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
        dietPlan: "ಆಹಾರ ಯೋಜನೆ",
        heroTitle: "ಕ್ಲಿನಿಕ್ ಭೇಟಿಗಳನ್ನು ಮಾಡಿ",
        heroTitleHighlight: "ಸ್ಮಾರ್ಟ್",
        heroTitleEnd: ", ಸುಗಮ ಮತ್ತು ಒತ್ತಡ ರಹಿತ",
        heroSubtitle: "ಆರೋಗ್ಯ ಮಿತ್ರ ರೋಗಿಗಳ ಸರತಿ ನಿರ್ವಹಣೆಯಿಂದ AI ಕಾಯುವ ಸಮಯದ ಮುನ್ಸೂಚನೆಯವರೆಗೆ ಎಲ್ಲವನ್ನೂ ನಿರ್ವಹಿಸುತ್ತದೆ।",
        aiWaitTime: "AI ಕಾಯುವ ಸಮಯ ಮುನ್ಸೂಚನೆ",
        aiWaitDesc: "ಮೆಷಿನ್ ಲರ್ನಿಂಗ್ ಮಾದರಿಗಳು ನೀವು ಎಷ್ಟು ಸಮಯ ಕಾಯಬೇಕು ಎಂದು ನಿಖರವಾಗಿ ಮುನ್ಸೂಚಿಸುತ್ತವೆ।",
        easyBooking: "ಸುಲಭ ಬುಕಿಂಗ್",
        easyBookingDesc: "ವೆಬ್‌ಸೈಟ್, ಅಪ್ಲಿಕೇಶನ್ ಅಥವಾ ಫೋನ್ ಕರೆಯ ಮೂಲಕ ಬುಕ್ ಮಾಡಿ।",
        secureRecords: "ಸುರಕ್ಷಿತ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
        secureRecordsDesc: "ಕ್ಲೌಡ್‌ನಲ್ಲಿ ವೈದ್ಯಕೀಯ ವರದಿಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ವೀಕ್ಷಿಸಿ।",
        smartQueue: "ಸ್ಮಾರ್ಟ್ ಸರತಿ ನಿರ್ವಹಣೆ",
        smartQueueDesc: "ರೋಗಿಗಳಿಗೆ ನೈಜ-ಸಮಯದ ಟೋಕನ್ ಸ್ಥಿತಿ ಮತ್ತು ಅಂದಾಜು ಕಾಯುವ ಸಮಯ।",
        featuresHeader: "ನಿಮಗಾಗಿ ನಿರ್ಮಿಸಲಾದ ವೈಶಿಷ್ಟ್ಯಗಳು",
        whyChoose: "ಆರೋಗ್ಯ ಮಿತ್ರವನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
        profile: "ಪ್ರೊಫೈಲ್",
        settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        logout: "ಲಾಗ್ ಔಟ್",
        patients: "ರೋಗಿಗಳು",
        appointments: "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು",
        reports: "ವರದಿಗಳು",
        queue: "ಸರತಿ",
        search: "ಹುಡುಕಿ",
        notifications: "ಅಧಿಸೂಚನೆಗಳು",
        home: "ಹೋಮ್"
    },
    ml: {
        appName: "ആരോഗ്യ മിത്ര",
        findDoctorsTitle: "ഡോക്ടർമാരെ കണ്ടെത്തുക",
        findDoctorsSubtitle: "ലഭ്യമായ ഡോക്ടർമാരെയും അവരുടെ ക്ലിനിക്കുകളെയും കാണുക",
        doctorName: "ഡോക്ടറുടെ പേര്",
        doctorSpecialization: "സ്പെഷ്യലൈസേഷൻ",
        doctorClinic: "ക്ലിനിക്ക്/ആശുപത്രി",
        login: "ലോഗിൻ",
        register: "രജിസ്റ്റർ",
        getStarted: "ആരംഭിക്കുക",
        dashboard: "ഡാഷ്ബോർഡ്",
        patientsQueue: "ക്യൂവിലുള്ള രോഗികൾ",
        avgWaitTime: "ശരാശരി കാത്തിരിപ്പ് സമയം",
        bookAppointment: "അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്യുക",
        welcome: "സ്വാഗതം",
        emergencyMode: "അടിയന്തര മോഡ്",
        stopEmergency: "അടിയന്തര മോഡ് നിർത്തുക",
        triggerEmergency: "അടിയന്തര മോഡ് ആരംഭിക്കുക",
        goodMorning: "സുപ്രഭാതം",
        upcoming: "വരാനിരിക്കുന്ന",
        healthRecords: "ആരോഗ്യ രേഖകൾ",
        dietPlan: "ഭക്ഷണ ക്രമം",
        heroTitle: "ക്ലിനിക്ക് സന്ദർശനങ്ങൾ ആക്കുക",
        heroTitleHighlight: "സ്മാർട്ട്",
        heroTitleEnd: ", എളുപ്പവും സമ്മർദ്ദരഹിതവുമാക്കുക",
        heroSubtitle: "ആരോഗ്യ മിത്ര രോഗി ക്യൂ മാനേജ്മെന്റ് മുതൽ AI കാത്തിരിപ്പ് സമയ പ്രവചനം വരെ എല്ലാം കൈകാര്യം ചെയ്യുന്നു।",
        aiWaitTime: "AI കാത്തിരിപ്പ് സമയ പ്രവചനം",
        aiWaitDesc: "മെഷീൻ ലേണിംഗ് മോഡലുകൾ നിങ്ങൾ എത്ര സമയം കാത്തിരിക്കേണ്ടി വരുമെന്ന് കൃത്യമായി പ്രവചിക്കുന്നു।",
        easyBooking: "എളുപ്പമുള്ള ബുക്കിംഗ്",
        easyBookingDesc: "വെബ്സൈറ്റ്, ആപ്പ് അല്ലെങ്കിൽ ലളിതമായ ഫോൺ കോൾ വഴി ബുക്ക് ചെയ്യുക।",
        secureRecords: "സുരക്ഷിത ആരോഗ്യ രേഖകൾ",
        secureRecordsDesc: "ക്ലൗഡിൽ മെഡിക്കൽ റിപ്പോർട്ടുകൾ സുരക്ഷിതമായി അപ്ലോഡ് ചെയ്യുകയും കാണുകയും ചെയ്യുക।",
        smartQueue: "സ്മാർട്ട് ക്യൂ മാനേജ്മെന്റ്",
        smartQueueDesc: "രോഗികൾക്കായി തത്സമയ ടോക്കൺ സ്റ്റാറ്റസും കണക്കാക്കിയ കാത്തിരിപ്പ് സമയവും।",
        featuresHeader: "നിങ്ങൾക്കായി നിർമ്മിച്ച സവിശേഷതകൾ",
        whyChoose: "എന്തുകൊണ്ട് ആരോഗ്യ മിത്ര തിരഞ്ഞെടുക്കണം?",
        profile: "പ്രൊഫൈൽ",
        settings: "സെറ്റിംഗ്സ്",
        logout: "ലോഗൗട്ട്",
        patients: "രോഗികൾ",
        appointments: "അപ്പോയിന്റ്മെന്റുകൾ",
        reports: "റിപ്പോർട്ടുകൾ",
        queue: "ക്യൂ",
        search: "തിരയുക",
        notifications: "അറിയിപ്പുകൾ",
        home: "ഹോം"
    },
    pa: {
        appName: "ਸਿਹਤ ਮਿੱਤਰ",
        findDoctorsTitle: "ਡਾਕਟਰ ਲੱਭੋ",
        findDoctorsSubtitle: "ਉਪਲਬਧ ਡਾਕਟਰ ਅਤੇ ਉਹਨਾਂ ਦੇ ਕਲੀਨਿਕ ਵੇਖੋ",
        doctorName: "ਡਾਕਟਰ ਦਾ ਨਾਮ",
        doctorSpecialization: "ਵਿਸ਼ੇਸ਼ਤਾ",
        doctorClinic: "ਕਲੀਨਿਕ/ਹਸਪਤਾਲ",
        login: "ਲੌਗ ਇਨ",
        register: "ਰਜਿਸਟਰ",
        getStarted: "ਸ਼ੁਰੂ ਕਰੋ",
        dashboard: "ਡੈਸ਼ਬੋਰਡ",
        patientsQueue: "ਕਤਾਰ ਵਿੱਚ ਮਰੀਜ਼",
        avgWaitTime: "ਔਸਤ ਉਡੀਕ ਸਮਾਂ",
        bookAppointment: "ਅਪਾਇੰਟਮੈਂਟ ਬੁੱਕ ਕਰੋ",
        welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
        emergencyMode: "ਐਮਰਜੈਂਸੀ ਮੋਡ",
        stopEmergency: "ਐਮਰਜੈਂਸੀ ਮੋਡ ਬੰਦ ਕਰੋ",
        triggerEmergency: "ਐਮਰਜੈਂਸੀ ਮੋਡ ਚਾਲੂ ਕਰੋ",
        goodMorning: "ਸ਼ੁਭ ਸਵੇਰ",
        upcoming: "ਆਉਣ ਵਾਲੇ",
        healthRecords: "ਸਿਹਤ ਰਿਕਾਰਡ",
        dietPlan: "ਖੁਰਾਕ ਯੋਜਨਾ",
        heroTitle: "ਕਲੀਨਿਕ ਮੁਲਾਕਾਤਾਂ ਨੂੰ ਬਣਾਓ",
        heroTitleHighlight: "ਸਮਾਰਟ",
        heroTitleEnd: ", ਸੌਖਾ ਅਤੇ ਤਣਾਅ-ਮੁਕਤ",
        heroSubtitle: "ਸਿਹਤ ਮਿੱਤਰ ਮਰੀਜ਼ ਕਤਾਰ ਪ੍ਰਬੰਧਨ ਤੋਂ ਲੈ ਕੇ AI ਉਡੀਕ ਸਮੇਂ ਦੀ ਭਵਿੱਖਬਾਣੀ ਤੱਕ ਸਭ ਕੁਝ ਸੰਭਾਲਦਾ ਹੈ।",
        aiWaitTime: "AI ਉਡੀਕ ਸਮੇਂ ਦੀ ਭਵਿੱਖਬਾਣੀ",
        aiWaitDesc: "ਮਸ਼ੀਨ ਲਰਨਿੰਗ ਮਾਡਲ ਸਹੀ ਤਰ੍ਹਾਂ ਦੱਸਦੇ ਹਨ ਕਿ ਤੁਹਾਨੂੰ ਕਿੰਨਾ ਸਮਾਂ ਉਡੀਕਣਾ ਪਵੇਗਾ।",
        easyBooking: "ਆਸਾਨ ਬੁਕਿੰਗ",
        easyBookingDesc: "ਵੈੱਬਸਾਈਟ, ਐਪ ਜਾਂ ਸਿੱਧੇ ਫੋਨ ਕਾਲ ਰਾਹੀਂ ਬੁੱਕ ਕਰੋ।",
        secureRecords: "ਸੁਰੱਖਿਅਤ ਸਿਹਤ ਰਿਕਾਰਡ",
        secureRecordsDesc: "ਕਲਾਉਡ ਤੇ ਮੈਡੀਕਲ ਰਿਪੋਰਟਾਂ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਵੇਖੋ।",
        smartQueue: "ਸਮਾਰਟ ਕਤਾਰ ਪ੍ਰਬੰਧਨ",
        smartQueueDesc: "ਮਰੀਜ਼ਾਂ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਟੋਕਨ ਸਥਿਤੀ ਅਤੇ ਅੰਦਾਜ਼ਿਤ ਉਡੀਕ ਸਮਾਂ।",
        featuresHeader: "ਤੁਹਾਡੇ ਲਈ ਬਣਾਈਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
        whyChoose: "ਸਿਹਤ ਮਿੱਤਰ ਕਿਉਂ ਚੁਣੋ?",
        profile: "ਪ੍ਰੋਫਾਈਲ",
        settings: "ਸੈਟਿੰਗਾਂ",
        logout: "ਲੌਗ ਆਉਟ",
        patients: "ਮਰੀਜ਼",
        appointments: "ਅਪਾਇੰਟਮੈਂਟਸ",
        reports: "ਰਿਪੋਰਟਾਂ",
        queue: "ਕਤਾਰ",
        search: "ਖੋਜੋ",
        notifications: "ਸੂਚਨਾਵਾਂ",
        home: "ਹੋਮ"
    },
    or: {
        appName: "ସ୍ୱାସ୍ଥ୍ୟ ମିତ୍ର",
        findDoctorsTitle: "ଡାକ୍ତର ଖୋଜନ୍ତୁ",
        findDoctorsSubtitle: "ଉପଲବ୍ଧ ଡାକ୍ତର ଏବଂ ସେମାନଙ୍କର କ୍ଲିନିକ୍ ଦେଖନ୍ତୁ",
        doctorName: "ଡାକ୍ତରଙ୍କ ନାମ",
        doctorSpecialization: "ବିଶେଷଜ୍ଞତା",
        doctorClinic: "କ୍ଲିନିକ୍/ହସ୍ପିଟାଲ୍",
        login: "ଲଗ୍ ଇନ୍",
        register: "ପଞ୍ଜିକରଣ",
        getStarted: "ଆରମ୍ଭ କରନ୍ତୁ",
        dashboard: "ଡ୍ୟାସବୋର୍ଡ",
        patientsQueue: "ଧାଡିରେ ରୋଗୀ",
        avgWaitTime: "ହାରାହାରି ଅପେକ୍ଷା ସମୟ",
        bookAppointment: "ନିଯୁକ୍ତି ବୁକ୍ କରନ୍ତୁ",
        welcome: "ସ୍ୱାଗତ",
        emergencyMode: "ଜରୁରୀକାଳୀନ ମୋଡ୍",
        stopEmergency: "ଜରୁରୀକାଳୀନ ମୋଡ୍ ବନ୍ଦ କରନ୍ତୁ",
        triggerEmergency: "ଜରୁରୀକାଳୀନ ମୋଡ୍ ଆରମ୍ଭ କରନ୍ତୁ",
        goodMorning: "ଶୁଭ ସକାଳ",
        upcoming: "ଆଗାମୀ",
        healthRecords: "ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ",
        dietPlan: "ଡାଏଟ୍ ପ୍ଲାନ୍",
        heroTitle: "କ୍ଲିନିକ୍ ପରିଦର୍ଶନକୁ କରନ୍ତୁ",
        heroTitleHighlight: "ସ୍ମାର୍ଟ",
        heroTitleEnd: ", ସହଜ ଏବଂ ଚାପମୁକ୍ତ",
        heroSubtitle: "ସ୍ୱାସ୍ଥ୍ୟ ମିତ୍ର ରୋଗୀ ଧାଡି ପରିଚାଳନାରୁ AI ଅପେକ୍ଷା ସମୟ ପୂର୍ବାନୁମାନ ପର୍ଯ୍ୟନ୍ତ ସବୁକିଛି ପରିଚାଳନା କରେ।",
        aiWaitTime: "AI ଅପେକ୍ଷା ସମୟ ପୂର୍ବାନୁମାନ",
        aiWaitDesc: "ମେସିନ୍ ଲର୍ନିଂ ମଡେଲଗୁଡିକ ଆପଣ କେତେ ସମୟ ଅପେକ୍ଷା କରିବେ ତାହା ସଠିକ୍ ଭାବରେ ପୂର୍ବାନୁମାନ କରନ୍ତି।",
        easyBooking: "ସହଜ ବୁକିଂ",
        easyBookingDesc: "ୱେବସାଇଟ୍, ଆପ୍ ବା ସରଳ ଫୋନ୍ କଲ୍ ମାଧ୍ୟମରେ ବୁକ୍ କରନ୍ତୁ।",
        secureRecords: "ସୁରକ୍ଷିତ ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡ",
        secureRecordsDesc: "କ୍ଲାଉଡ୍‌ରେ ମେଡିକାଲ୍ ରିପୋର୍ଟଗୁଡିକୁ ସୁରକ୍ଷିତ ଭାବରେ ଅପଲୋଡ୍ କରନ୍ତୁ ଏବଂ ଦେଖନ୍ତୁ।",
        smartQueue: "ସ୍ମାର୍ଟ ଧାଡି ପରିଚାଳନା",
        smartQueueDesc: "ରୋଗୀମାନଙ୍କ ପାଇଁ ରିଅଲ୍-ଟାଇମ୍ ଟୋକେନ୍ ସ୍ଥିତି ଏବଂ ଆନୁମାନିକ ଅପେକ୍ଷା ସମୟ।",
        featuresHeader: "ଆପଣଙ୍କ ପାଇଁ ନିର୍ମିତ ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ",
        whyChoose: "କାହିଁକି ସ୍ୱାସ୍ଥ୍ୟ ମିତ୍ର ବାଛନ୍ତୁ?",
        profile: "ପ୍ରୋଫାଇଲ୍",
        settings: "ସେଟିଂସ୍",
        logout: "ଲଗ୍ ଆଉଟ୍",
        patients: "ରୋଗୀ",
        appointments: "ନିଯୁକ୍ତି",
        reports: "ରିପୋର୍ଟ",
        queue: "ଧାଡି",
        search: "ଖୋଜନ୍ତୁ",
        notifications: "ବିଜ୍ଞପ୍ତି",
        home: "ହୋମ୍"
    },
    as: {
        appName: "স্বাস্থ্য মিত্ৰ",
        findDoctorsTitle: "চিকিৎসক বিচাৰক",
        findDoctorsSubtitle: "উপলব্ধ চিকিৎসক আৰু তেওঁলোকৰ ক্লিনিক চাওক",
        doctorName: "চিকিৎসকৰ নাম",
        doctorSpecialization: "বিশেষজ্ঞতা",
        doctorClinic: "ক্লিনিক/চিকিৎসালয়",
        login: "লগ ইন",
        register: "পঞ্জীয়ন",
        getStarted: "আৰম্ভ কৰক",
        dashboard: "ডেশবৰ্ড",
        patientsQueue: "শাৰীত ৰোগী",
        avgWaitTime: "গড় অপেক্ষাৰ সময়",
        bookAppointment: "এপইন্টমেণ্ট বুক কৰক",
        welcome: "স্বাগতম",
        emergencyMode: "জৰুৰীকালীন অৱস্থা",
        stopEmergency: "জৰুৰীকালীন অৱস্থা বন্ধ কৰক",
        triggerEmergency: "জৰুৰীকালীন অৱস্থা আৰম্ভ কৰক",
        goodMorning: "সুপ্ৰভাত",
        upcoming: "আগন্তুক",
        healthRecords: "স্বাস্থ্য ৰেকৰ্ড",
        dietPlan: "ডায়েট প্লেন",
        heroTitle: "ক্লিনিক ভিজিট কৰক",
        heroTitleHighlight: "স্মাৰ্ট",
        heroTitleEnd: ", সহজ আৰু চাপমুক্ত",
        heroSubtitle: "স্বাস্থ্য মিত্ৰই ৰোগীৰ শাৰী ব্যৱস্থাপনাৰ পৰা AI অপেক্ষাৰ সময় পূৰ্বাভাসলৈকে সকলো পৰিচালনা কৰে।",
        aiWaitTime: "AI অপেক্ষাৰ সময় পূৰ্বাভাস",
        aiWaitDesc: "মেচিন লাৰ্নিং মডেলে আপুনি কিমান সময় অপেক্ষা কৰিব লাগিব সেয়া সঠিকভাৱে পূৰ্বাভাস দিয়ে।",
        easyBooking: "সহজ বুকিং",
        easyBookingDesc: "ৱেবছাইট, এপ বা সাধাৰণ ফোন কলৰ জৰিয়তে বুক কৰক।",
        secureRecords: "সুৰক্ষিত স্বাস্থ্য ৰেকৰ্ড",
        secureRecordsDesc: "ক্লাউডত চিকিৎসা প্ৰতিবেদন সুৰক্ষিতভাৱে আপলোড কৰক আৰু চাওক।",
        smartQueue: "স্মাৰ্ট শাৰী ব্যৱস্থাপনা",
        smartQueueDesc: "ৰোগীসকলৰ বাবে ৰিয়েল-টাইম টোকেন স্থিতি আৰু আনুমানিক অপেক্ষাৰ সময়।",
        featuresHeader: "আপোনাৰ বাবে নিৰ্মিত বৈশিষ্ট্যসমূহ",
        whyChoose: "কিয় স্বাস্থ্য মিত্ৰ বাছনি কৰিব?",
        profile: "প্ৰ'ফাইল",
        settings: "ছেটিংছ",
        logout: "লগ আউট",
        patients: "ৰোগী",
        appointments: "এপইন্টমেণ্ট",
        reports: "প্ৰতিবেদন",
        queue: "শাৰী",
        search: "বিচাৰক",
        notifications: "জাননী",
        home: "হোম"
    },
    ur: {
        appName: "صحت مترا",
        findDoctorsTitle: "ڈاکٹر تلاش کریں",
        findDoctorsSubtitle: "دستیاب ڈاکٹرز اور ان کے کلینک دیکھیں",
        doctorName: "ڈاکٹر کا نام",
        doctorSpecialization: "مہارت",
        doctorClinic: "کلینک/ہسپتال",
        login: "لاگ ان",
        register: "رجسٹر",
        getStarted: "شروع کریں",
        dashboard: "ڈیش بورڈ",
        patientsQueue: "قطار میں مریض",
        avgWaitTime: "اوسط انتظار کا وقت",
        bookAppointment: "اپائنٹمنٹ بک کریں",
        welcome: "خوش آمدید",
        emergencyMode: "ہنگامی حالت",
        stopEmergency: "ہنگامی حالت روکیں",
        triggerEmergency: "ہنگامی حالت شروع کریں",
        goodMorning: "صبح بخیر",
        upcoming: "آنے والا",
        healthRecords: "صحت کا ریکارڈ",
        dietPlan: "ڈائٹ پلان",
        heroTitle: "کلینک کے دورے بنائیں",
        heroTitleHighlight: "سمارٹ",
        heroTitleEnd: "، آسان اور تناؤ سے پاک",
        heroSubtitle: "صحت مترا مریضوں کی قطار کے انتظام سے لے کر AI انتظار کے وقت کی پیشن گوئی تک سب کچھ سنبھالتا ہے۔",
        aiWaitTime: "AI انتظار کے وقت کی پیشن گوئی",
        aiWaitDesc: "مشین لرننگ ماڈل بالکل درست طریقے سے بتاتے ہیں کہ آپ کو کتنا انتظار کرنا ہوگا۔",
        easyBooking: "آسان بکنگ",
        easyBookingDesc: "ویب سائٹ، ایپ یا صرف ایک فون کال کے ذریعے بک کریں۔",
        secureRecords: "محفوظ صحت کے ریکارڈ",
        secureRecordsDesc: "کلاؤڈ پر طبی رپورٹیں محفوظ طریقے سے اپ لوڈ کریں اور دیکھیں۔",
        smartQueue: "سمارٹ قطار کا انتظام",
        smartQueueDesc: "مریضوں کے لیے ریئل ٹائم ٹوکن اسٹیٹس اور تخمینہ شدہ انتظار کا وقت۔",
        featuresHeader: "آپ کے لیے بنائی گئی خصوصیات",
        whyChoose: "صحت مترا کیوں منتخب کریں؟",
        profile: "پروفائل",
        settings: "ترتیبات",
        logout: "لاگ آؤٹ",
        patients: "مریض",
        appointments: "اپائنٹمنٹس",
        reports: "رپورٹیں",
        queue: "قطار",
        search: "تلاش",
        notifications: "اطلاعات",
        home: "ہوم"
    },
    sa: {
        appName: "स्वास्थ्यमित्रम्",
        findDoctorsTitle: "वैद्यान् अन्विष्यतु",
        findDoctorsSubtitle: "उपलब्धान् वैद्यान् तेषां चिकित्सालयान् च पश्यतु",
        doctorName: "वैद्यस्य नाम",
        doctorSpecialization: "विशेषज्ञता",
        doctorClinic: "चिकित्सालयः/आरोग्यशाला",
        login: "प्रवेशः",
        register: "पञ्जीकरणम्",
        getStarted: "आरभत",
        dashboard: "फलकम्",
        patientsQueue: "पङ्क्तौ रोगिणः",
        avgWaitTime: "सरासरी प्रतीक्षासमयः",
        bookAppointment: "नियुक्तिं रचयतु",
        welcome: "स्वागतम्",
        emergencyMode: "आपात्कालीन स्थितिः",
        stopEmergency: "आपात्कालीन स्थितिं स्थगयतु",
        triggerEmergency: "आपात्कालीन स्थितिं आरभत",
        goodMorning: "सुप्रभातम्",
        upcoming: "आगामि",
        healthRecords: "स्वास्थ्य अभिलेखाः",
        dietPlan: "आहार योजना",
        heroTitle: "चिकित्सालय भ्रमणं कुर्वन्तु",
        heroTitleHighlight: "बुद्धिमत्",
        heroTitleEnd: ", सुगमं तनावरहितं च",
        heroSubtitle: "स्वास्थ्यमित्रम् रोगिणां पङ्क्ति प्रबन्धनात् AI प्रतीक्षासमय पूर्वानुमानं यावत् सर्वं प्रबन्धयति।",
        aiWaitTime: "AI प्रतीक्षासमय पूर्वानुमानम्",
        aiWaitDesc: "यन्त्रशिक्षण प्रतिमानाः भवन्तः कियत्कालं प्रतीक्षितव्यम् इति सम्यक् पूर्वानुमानं कुर्वन्ति।",
        easyBooking: "सुगम आरक्षणम्",
        easyBookingDesc: "जालस्थलेन, अनुप्रयोगेन वा सरल दूरवाणी कथनेन आरक्षयतु।",
        secureRecords: "सुरक्षित स्वास्थ्य अभिलेखाः",
        secureRecordsDesc: "मेघे चिकित्सा प्रतिवेदनानि सुरक्षितरूपेण उत्तारयतु पश्यतु च।",
        smartQueue: "बुद्धिमत् पङ्क्ति प्रबन्धनम्",
        smartQueueDesc: "रोगिभ्यः वास्तविक-समय चिह्न स्थितिः अनुमानितप्रतीक्षासमयः च।",
        featuresHeader: "भवद्भ्यः निर्मिताः विशेषताः",
        whyChoose: "किमर्थं स्वास्थ्यमित्रं वृणुत?",
        profile: "परिचयपत्रम्",
        settings: "विन्यासाः",
        logout: "निर्गमनम्",
        patients: "रोगिणः",
        appointments: "नियुक्तयः",
        reports: "प्रतिवेदनानि",
        queue: "पङ्क्तिः",
        search: "अन्वेषणम्",
        notifications: "सूचनाः",
        home: "गृहम्"
    },
    mai: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डाक्टर खोजू",
        findDoctorsSubtitle: "उपलब्ध डाक्टर आ हुनकर क्लिनिक देखू",
        doctorName: "डाक्टरक नाम",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "पंजीकरण",
        getStarted: "शुरू करू",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतारमे रोगी",
        avgWaitTime: "औसत प्रतीक्षा समय",
        bookAppointment: "अपॉइंटमेंट बुक करू",
        welcome: "स्वागत अछि",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोकू",
        triggerEmergency: "आपातकालीन मोड शुरू करू",
        goodMorning: "सुप्रभात",
        upcoming: "आगामी",
        healthRecords: "स्वास्थ्य रिकॉर्ड",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक भ्रमण करू",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सहज आ तनावमुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र रोगी कतार प्रबंधनसँ लऽ कऽ AI प्रतीक्षा समय पूर्वानुमान धरि सब किछु संभालैत अछि।",
        aiWaitTime: "AI प्रतीक्षा समय पूर्वानुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बताबैत अछि जे अहाँ कतेक काल इंतजार करब।",
        easyBooking: "सहज बुकिंग",
        easyBookingDesc: "वेबसाइट, एप वा फोन कॉल द्वारा बुक करू।",
        secureRecords: "सुरक्षित स्वास्थ्य रिकॉर्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित रूपेँ अपलोड करू आ देखू।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "रोगी सभक लेल रियल-टाइम टोकन स्थिति आ अनुमानित प्रतीक्षा समय।",
        featuresHeader: "अहाँक लेल बनाओल गेल सुविधा सभ",
        whyChoose: "किएक चुनू स्वास्थ्य-मित्र?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "रोगी सभ",
        appointments: "अपॉइंटमेंट सभ",
        reports: "रिपोर्ट सभ",
        queue: "कतार",
        search: "खोजू",
        notifications: "सूचना सभ",
        home: "होम"
    },
    ks: {
        appName: "صحت مترا",
        findDoctorsTitle: "ڈاکٹر لبو",
        findDoctorsSubtitle: "دستیاب ڈاکٹر تہ تمن ہندۍ کلینک وچھو",
        doctorName: "ڈاکٹرک ناو",
        doctorSpecialization: "خاص مہارت",
        doctorClinic: "کلینک/ہسپتال",
        login: "لاگ ان",
        register: "رجسٹر",
        getStarted: "شروع کریو",
        dashboard: "ڈیش بورڈ",
        patientsQueue: "قطارس منز مریض",
        avgWaitTime: "اوسط انتظارک وقت",
        bookAppointment: "اپائنٹمنٹ بک کریو",
        welcome: "خوش آمدید",
        emergencyMode: "ہنگامی موڈ",
        stopEmergency: "ہنگامی موڈ روکिव",
        triggerEmergency: "ہنگامی موڈ شروع کریو",
        goodMorning: "صبح بخیر",
        upcoming: "یوان",
        healthRecords: "صحتک ریکارڈ",
        dietPlan: "ڈائٹ پلان",
        heroTitle: "کلینک دورہ بناؤ",
        heroTitleHighlight: "سمارٹ",
        heroTitleEnd: "، سہل تہ تناو آزاد",
        heroSubtitle: "صحت مترا مریضن ہند قطار انتظامہ پیٹھ AI انتظار وقتک پیش گوئی تام سارے کنہہ سنبھالان چھ۔",
        aiWaitTime: "AI انتظار وقتک پیش گوئی",
        aiWaitDesc: "مشین لرننگ ماڈل بیان چھ کرن زِ توہہ کتہ وقت انتظار کرن۔",
        easyBooking: "آسان بکنگ",
        easyBookingDesc: "ویب سائٹ، ایپ یا فون کال ذریعہ بک کریو۔",
        secureRecords: "محفوظ صحت ریکارڈ",
        secureRecordsDesc: "کلاؤڈس منز میڈیکل رپورٹ محفوظ طریقہ سان اپ لوڈ کریو تہ وچھیو۔",
        smartQueue: "سمارٹ قطار انتظام",
        smartQueueDesc: "مریضن باپتھ ریل ٹائم ٹوکن حالت تہ تخمینہ شدہ انتظار وقت۔",
        featuresHeader: "توہہ خاطرہ بناول خصوصیت",
        whyChoose: "کیازِ صحت مترا ژھاریو؟",
        profile: "پروفائل",
        settings: "سیٹنگ",
        logout: "لاگ آؤٹ",
        patients: "مریض",
        appointments: "اپائنٹمنٹ",
        reports: "رپورٹ",
        queue: "قطار",
        search: "تلاش",
        notifications: "اطلاع",
        home: "ہوم"
    },
    kok: {
        appName: "स्वास्थ्य मित्र",
        findDoctorsTitle: "डॉक्टर सोद",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर आनी तांचे क्लिनिक पळयात",
        doctorName: "डॉक्टराचें नांव",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/हॉस्पिटल",
        login: "लॉग इन",
        register: "नोंदणी",
        getStarted: "सुरू करात",
        dashboard: "डॅशबोर्ड",
        patientsQueue: "रांगेतले दुयेंस",
        avgWaitTime: "सरासरी वाट पळोवपाचो वेळ",
        bookAppointment: "अपॉइंटमेंट बुक करात",
        welcome: "येवकार",
        emergencyMode: "आणीबाणी मोड",
        stopEmergency: "आणीबाणी मोड थांबयात",
        triggerEmergency: "आणीबाणी मोड सुरू करात",
        goodMorning: "बरो सकाळी",
        upcoming: "फुडलो",
        healthRecords: "भलायकी नोंदी",
        dietPlan: "आहार येवजण",
        heroTitle: "क्लिनिक भेट करात",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सोपें आनी तणावमुक्त",
        heroSubtitle: "स्वास्थ्य मित्र दुयेंस रांग व्यवस्थापनासावन AI वाट पळोवपाची वेळ अंदाज मेरेन सगळें संभाळता।",
        aiWaitTime: "AI वाट पळोवपाची वेळ अंदाज",
        aiWaitDesc: "मशीन लर्निंग मॉडेलान सांगतात कितलो वेळ वाट पळोवची पडटली।",
        easyBooking: "सोपें बुकिंग",
        easyBookingDesc: "वेबसाईट, अॅप वा फोन कॉलान बुक करात।",
        secureRecords: "सुरक्षीत भलायकी नोंदी",
        secureRecordsDesc: "क्लाऊडार मेडिकल रिपोर्ट सुरक्षीतपणान अपलोड करात आनी पळयात।",
        smartQueue: "स्मार्ट रांग व्यवस्थापन",
        smartQueueDesc: "दुयेंसांक खातीर रियल-टाईम टोकन स्थिती आनी अंदाजीत वाट पळोवपाचो वेळ।",
        featuresHeader: "तुमचे खातीर तयार केल्ले वैशिष्ट्य",
        whyChoose: "कित्याक वेंचूंक स्वास्थ्य मित्र?",
        profile: "प्रोफायल",
        settings: "सेटिंग्ज",
        logout: "लॉग आऊट",
        patients: "दुयेंस",
        appointments: "अपॉइंटमेंट",
        reports: "अहवाल",
        queue: "रांग",
        search: "सोद",
        notifications: "सूचना",
        home: "घर"
    },
    sd: {
        appName: "صحت-مِتر",
        findDoctorsTitle: "ڊاڪٽر ڳوليو",
        findDoctorsSubtitle: "موجود ڊاڪٽر ۽ سندن ڪلينڪ ڏسو",
        doctorName: "ڊاڪٽر جو نالو",
        doctorSpecialization: "خاصيت",
        doctorClinic: "ڪلينڪ/اسپتال",
        login: "لاگ ان",
        register: "رجسٽر ڪريو",
        getStarted: "شروعات ڪريو",
        dashboard: "ڊيش بورڊ",
        patientsQueue: "قطار ۾ مريض",
        avgWaitTime: "اوسط انتظار وقت",
        bookAppointment: "اپائنٽمينٽ بڪ ڪريو",
        welcome: "ڀليڪار",
        emergencyMode: "ايمرجنسي موڊ",
        stopEmergency: "ايمرجنسي موڊ روڪيو",
        triggerEmergency: "ايمرجنسي موڊ شروع ڪريو",
        goodMorning: "صبح جو سلام",
        upcoming: "ايندڙ",
        healthRecords: "صحت جا رڪارڊ",
        dietPlan: "غذا جو منصوبو",
        heroTitle: "ڪلينڪ جو دورو بڻايو",
        heroTitleHighlight: "هوشيار",
        heroTitleEnd: ", آسان ۽ بغير تڪليف جي",
        heroSubtitle: "صحت-مِتر مريضن جي قطار سنڀالڻ کان وٺي AI انتظار وقت اڳڪٿي تائين هر شيءِ منظم ڪري ٿو.",
        aiWaitTime: "AI انتظار وقت اڳڪٿي",
        aiWaitDesc: "مشين لرننگ ماڊل ٻڌائن ٿا ته اوهان کي ڪيترو انتظار ڪرڻو پوندو.",
        easyBooking: "آسان بڪنگ",
        easyBookingDesc: "ويب سائيٽ، ايپ يا فون ڪال سان فوري بڪ ڪريو.",
        secureRecords: "محفوظ صحت رڪارڊ",
        secureRecordsDesc: "ميڊيڪل رپورٽون ڪلاوڊ تي محفوظ طريقي سان اپلوڊ ۽ ڏسو.",
        smartQueue: "ساراهه قطار انتظام",
        smartQueueDesc: "مريضن لاءِ ريل ٽائيم ٽوڪن حالت ۽ اندازي وارو انتظار وقت.",
        featuresHeader: "توهان لاءِ تيار ڪيل خوبيون",
        whyChoose: "صحت-مِتر ڇو چونڊيو؟",
        profile: "پروفائل",
        settings: "سيٽنگز",
        logout: "لاگ آئوٽ",
        patients: "مريض",
        appointments: "اپائنٽمينٽس",
        reports: "رپورٽون",
        queue: "قطار",
        search: "ڳوليو",
        notifications: "نوٽيفڪيشن",
        home: "گهر"
    },
    mni: {
        appName: "স্বাস্থ্য মিত্র",
        findDoctorsTitle: "দক্তরশিং থীবিযু",
        findDoctorsSubtitle: "ফংবা দক্তর অমসুং মখোয়গী ক্লিনিকশিং উবা",
        doctorName: "দক্তরগী মমিং",
        doctorSpecialization: "স্পেসিয়েলাইজেসন",
        doctorClinic: "ক্লিনিক/হস্পিতেল",
        login: "লগ ইন",
        register: "রেজিস্তর",
        getStarted: "হৌদোকপিযু",
        dashboard: "দেশবোর্দ",
        patientsQueue: "ক্যুদা লৈবা অনাবশিং",
        avgWaitTime: "এভরেজ ঙাইবা মতম",
        bookAppointment: "এপোইন্টমেন্ত বুক তৌবিযু",
        welcome: "তরাম্না ওকচরি",
        emergencyMode: "ইমর্জেন্সি মোদ",
        stopEmergency: "ইমর্জেন্সি মোদ লেপপিয়ু",
        triggerEmergency: "ইমর্জেন্সি মোদ হৌদোকপিয়ু",
        goodMorning: "নুংঙাইবা নুমিৎ",
        upcoming: "লাক্কদৌরিবা",
        healthRecords: "হেল্থ রেকোর্দস",
        dietPlan: "দাইয়েত প্লান",
        heroTitle: "ক্লিনিক ভিজিত শেম্বা",
        heroTitleHighlight: "স্মার্ত",
        heroTitleEnd: ", ফজনা অমসুং স্ত্রেস ফ্রী",
        heroSubtitle: "স্বাস্থ্য মিত্রনা অনাবগী ক্যু মেনেজমেন্ত অসিদগী হৌদুনা AI ঙাইবা মতমগী প্রিদিক্সনফাওবা পুম্নমক পাংথোক্লি।",
        aiWaitTime: "AI ঙাইবা মতমগী প্রিদিক্সন",
        aiWaitDesc: "মেসিন লর্নিংগী মোদেলশিংনা নখোয়না কযা ঙাইবা মতম চংগদগে হায়বদু অচুম্বা ওইনা হায়বসি।",
        easyBooking: "ফজবা বুকিং",
        easyBookingDesc: "ওয়েবসাইত, এপ নত্রগা ফোন কোলগী মখাদা বুক তৌ।",
        secureRecords: "নিংথিনা থম্লিবা হেল্থ রেকোর্দস",
        secureRecordsDesc: "ক্লাউদদা মেদিকেল রিপোর্তশিং নিংথিনা আপলোদ তৌবা অমসুং উবা।",
        smartQueue: "স্মার্ত ক্যু মেনেজমেন্ত",
        smartQueueDesc: "অনাবশিংগিদমক রিয়েল-টাইম টোকেন স্তেতস অমসুং এস্তিমেত তৌরবা ঙাইবা মতম।",
        featuresHeader: "নখোয়গিদমকতা শেমগৎলবা ফিচরশিং",
        whyChoose: "করিগী স্বাস্থ্য মিত্র খনগনি?",
        profile: "প্রোফাইল",
        settings: "সেত্তিংস",
        logout: "লগ আউত",
        patients: "অনাবশিং",
        appointments: "এপোইন্টমেন্তশিং",
        reports: "রিপোর্তশিং",
        queue: "ক্যু",
        search: "থীবিযু",
        notifications: "নোতিফিকেসনশিং",
        home: "যুম"
    },
    ne: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डाक्टर खोज्नुहोस्",
        findDoctorsSubtitle: "उपलब्ध डाक्टर र तिनीहरूका क्लिनिक हेर्नुहोस्",
        doctorName: "डाक्टरको नाम",
        doctorSpecialization: "विशेषज्ञता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लग इन",
        register: "दर्ता",
        getStarted: "सुरु गर्नुहोस्",
        dashboard: "ड्यासबोर्ड",
        patientsQueue: "लाइनमा बिरामीहरू",
        avgWaitTime: "औसत प्रतीक्षा समय",
        bookAppointment: "अपोइन्टमेन्ट बुक गर्नुहोस्",
        welcome: "स्वागत छ",
        emergencyMode: "आपतकालीन मोड",
        stopEmergency: "आपतकालीन मोड रोक्नुहोस्",
        triggerEmergency: "आपतकालीन मोड सुरु गर्नुहोस्",
        goodMorning: "शुभ प्रभात",
        upcoming: "आगामी",
        healthRecords: "स्वास्थ्य रेकर्डहरू",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक भ्रमण बनाउनुहोस्",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सहज र तनावरहित",
        heroSubtitle: "स्वास्थ्य-मित्रले बिरामी लाइन व्यवस्थापनदेखि AI प्रतीक्षा समय पूर्वानुमानसम्म सबै कुरा सम्हाल्छ।",
        aiWaitTime: "AI प्रतीक्षा समय पूर्वानुमान",
        aiWaitDesc: "मेसिन लर्निङ मोडेलहरूले तपाईंले कति समय पर्खनुपर्ने हो भनी सही रूपमा भविष्यवाणी गर्छन्।",
        easyBooking: "सजिलो बुकिङ",
        easyBookingDesc: "वेबसाइट, एप वा सामान्य फोन कलमार्फत बुक गर्नुहोस्।",
        secureRecords: "सुरक्षित स्वास्थ्य रेकर्डहरू",
        secureRecordsDesc: "क्लाउडमा चिकित्सा रिपोर्टहरू सुरक्षित रूपमा अपलोड गर्नुहोस् र हेर्नुहोस्।",
        smartQueue: "स्मार्ट लाइन व्यवस्थापन",
        smartQueueDesc: "बिरामीहरूका लागि वास्तविक-समय टोकन स्थिति र अनुमानित प्रतीक्षा समय।",
        featuresHeader: "तपाईंका लागि निर्मित सुविधाहरू",
        whyChoose: "किन रोज्ने स्वास्थ्य-मित्र?",
        profile: "प्रोफाइल",
        settings: "सेटिङहरू",
        logout: "लग आउट",
        patients: "बिरामीहरू",
        appointments: "अपोइन्टमेन्टहरू",
        reports: "रिपोर्टहरू",
        queue: "लाइन",
        search: "खोज्नुहोस्",
        notifications: "सूचनाहरू",
        home: "होम"
    },
    doi: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डॉक्टर खोजो",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर अते ओनां दे क्लिनिक देखो",
        doctorName: "डॉक्टर दा नां",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "शुरू करो",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार च मरीज",
        avgWaitTime: "औसत इंतजार दा समां",
        bookAppointment: "अपॉइंटमेंट बुक करो",
        welcome: "स्वागत ऐ",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोको",
        triggerEmergency: "आपातकालीन मोड शुरू करो",
        goodMorning: "सुप्रभात",
        upcoming: "औने आला",
        healthRecords: "सेहत रिकार्ड",
        dietPlan: "डाइट प्लान",
        heroTitle: "क्लिनिक दी यात्रा बनाओ",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", आसान अते तनाव मुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र मरीज कतार संभालने तो AI इंतजार समय दी पहचाण तक हर कज करदा ऐ।",
        aiWaitTime: "AI इंतजार समय भविष्यवाणी",
        aiWaitDesc: "मशीन लर्निंग मॉडल दसदे ने तुसी किन्ने समय इंतजार करोगे।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, ऐप जा फोन कॉल नाल बुक करो।",
        secureRecords: "सुरक्षित सेहत रिकार्ड",
        secureRecordsDesc: "क्लाउड 'ते मेडिकल रिपोर्ट सुरक्षित तरीके नाल अपलोड करो अते देखो।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीजां लेई रियल-टाइम टोकन हालत अते अंदाजा इंतजार समां।",
        featuresHeader: "तुआडे लेई बनाइयां सुविधावां",
        whyChoose: "क्यों चुनो स्वास्थ्य-मित्र?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्ज",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजो",
        notifications: "सूचनाएं",
        home: "होम"
    },
    brx: {
        appName: "सावस्रि-मित्र",
        findDoctorsTitle: "डाक्तर हाबा",
        findDoctorsSubtitle: "लाबोनाय डाक्तर आरो बेंनानि क्लिनिक नाय लगोन",
        doctorName: "डाक्तरनि मुं",
        doctorSpecialization: "बिसेसे",
        doctorClinic: "क्लिनिक/हस्पिताल",
        login: "लग् इन",
        register: "रेजिस्टार",
        getStarted: "सुरु खालाम",
        dashboard: "डेशबर्ड",
        patientsQueue: "सारियाव दं",
        avgWaitTime: "गड़ नेनाय सम",
        bookAppointment: "अपोइन्टमेन्ट बुक खालाम",
        welcome: "बरायबाय",
        emergencyMode: "इमारजेन्सि मड",
        stopEmergency: "इमारजेन्सि मड बन्द खालाम",
        triggerEmergency: "इमारजेन्सि मड सुरु खालाम",
        goodMorning: "मोजां फुं",
        upcoming: "फैबाय थानाय",
        healthRecords: "सावस्रि रेकर्ड",
        dietPlan: "जानाय लोंनाय",
        heroTitle: "क्लिनिक बिहोन सोजु",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", सोरजु आरो थांनाखां",
        heroSubtitle: "सावस्रि-मित्रो रोगिनी सारि मुथायनि जोंगजोंगनोथि ब्राय AI नेनाय समनि अंदाजो गैया गोनां दं।",
        aiWaitTime: "AI नेनाय समनि अंदाज",
        aiWaitDesc: "मेसिन लर्निंग मोडेलखो नोंगोन जे नोंगे नेनाय समनायनो हागौ।",
        easyBooking: "सोजु बुकिं",
        easyBookingDesc: "वेबसाइट, एप जानि फोन कॉलनि जों बुक खालाम।",
        secureRecords: "सुरक्षा सावस्रि रेकर्ड",
        secureRecordsDesc: "क्लाउडाव मेडिकल रिपोर्ट सुरक्षा जाथाय नाय लगोन आरो थांखोन।",
        smartQueue: "स्मार्ट सारि मुथाय",
        smartQueueDesc: "रोगिनिफ्रि रियल-टाइम टोकन थाखो आरो अंदाजा नेनाय सम।",
        featuresHeader: "नोंथांनि थाखाय सोरजानाय गुवां",
        whyChoose: "सावस्रि-मित्र हेंडायफिन्नो नुडों?",
        profile: "प्रोफाइल",
        settings: "सेटिंस",
        logout: "लॉग आउट",
        patients: "रोगी",
        appointments: "अपोइन्टमेन्ट",
        reports: "रिपोर्ट",
        queue: "सारि",
        search: "नागिर",
        notifications: "नोटिफिकेसन",
        home: "घर"
    },
    sat: {
        appName: "ᱥᱣᱟᱥᱛᱷᱟ-ᱢᱤᱛᱨᱟ",
        findDoctorsTitle: "ᱫᱟᱞᱟᱜ ᱭᱚᱛᱚᱢ ᱠᱚ ᱟᱨᱦᱚᱸ",
        findDoctorsSubtitle: "ᱵᱟᱵᱚᱛ ᱫᱟᱞᱟᱜ ᱤᱧ ᱟᱨ ᱡᱟᱞᱟ ᱡᱷᱚᱛᱚ ᱛᱤᱱ ᱠᱷᱟᱴᱟᱣ",
        doctorName: "ᱫᱟᱞᱟᱜ ᱧᱩᱛᱩᱢ",
        doctorSpecialization: "ᱯᱟᱥᱱᱤᱡ",
        doctorClinic: "ᱠᱞᱤᱱᱤᱠ/ᱡᱷᱚᱛᱚ",
        login: "ᱵᱚᱞᱚ",
        register: "ᱨᱮᱡᱤᱥᱴᱚᱨ",
        getStarted: "ᱟᱹᱰᱤ ᱢᱮ",
        dashboard: "ᱰᱮᱥᱵᱚᱨᱰ",
        patientsQueue: "ᱥᱟᱨᱤ ᱨᱮ ᱫᱟᱞᱟᱜ",
        avgWaitTime: "ᱜᱚᱲ ᱛᱟᱺᱜᱤ ᱚᱠᱛᱚ",
        bookAppointment: "ᱟᱯᱚᱭᱮᱱᱴᱢᱮᱱᱴ ᱵᱩᱠ ᱢᱮ",
        welcome: "ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ",
        emergencyMode: "ᱡᱚᱨᱩᱨᱤ ᱢᱚᱰ",
        stopEmergency: "ᱡᱚᱨᱩᱨᱤ ᱢᱚᱰ ᱵᱚᱱᱫᱚᱭ ᱢᱮ",
        triggerEmergency: "ᱡᱚᱨᱩᱨᱤ ᱢᱚᱰ ᱮᱦᱚᱵ ᱢᱮ",
        goodMorning: "ᱥᱟᱹᱜᱩᱱ ᱥᱮᱛᱟᱜ",
        upcoming: "ᱦᱤᱡᱩᱜ ᱠᱟᱱ",
        healthRecords: "ᱥᱟᱹᱣᱥᱨᱤ ᱨᱮᱠᱚᱨᱰ",
        dietPlan: "ᱡᱚᱢ ᱧᱩ",
        heroTitle: "ᱠᱞᱤᱱᱤᱠ ᱵᱟᱵᱚᱛ ᱦᱟᱹᱞᱤᱧᱟ",
        heroTitleHighlight: "ᱥᱢᱟᱨᱛ",
        heroTitleEnd: ", ᱠᱟᱹᱥᱤᱛ ᱟᱨ ᱛᱤᱱ ᱵᱟᱭᱤᱱ",
        heroSubtitle: "ᱥᱣᱟᱥᱛᱷᱟ-ᱢᱤᱛᱨᱟ ᱫᱟᱞᱟᱜ ᱥᱟᱨᱤ ᱢᱮᱱᱟᱡᱟᱱ ᱠᱷᱚᱱ ᱠᱚ AI ᱟᱡᱷᱟᱨ ᱟᱫᱮᱨ ᱵᱟᱭ ᱛᱤᱱ ᱦᱟᱹᱞᱤᱧᱟ।",
        aiWaitTime: "AI ᱟᱡᱷᱟᱨ ᱟᱫᱮᱨ",
        aiWaitDesc: "ᱢᱮᱥᱤᱱ ᱞᱟᱨᱱᱤᱝ ᱢᱚᱰᱮᱞ ᱦᱟᱹᱞᱤᱧᱟ ᱟᱹᱱᱤ ᱪᱟᱹᱞ ᱦᱩᱭ ᱥᱮ ᱟᱡᱷᱟᱨ ᱚᱠᱟᱛᱮ।",
        easyBooking: "ᱟᱢ ᱵᱩᱠᱤᱝ",
        easyBookingDesc: "ᱣᱮᱵᱥᱟᱭᱛ, ᱮᱯ ᱟᱨ ᱯᱷᱚᱱ ᱠᱚᱞ ᱨᱮ ᱵᱩᱠ ᱢᱮ।",
        secureRecords: "ᱥᱩᱨᱠᱟᱹ ᱥᱟᱹᱣᱥᱨᱤ ᱨᱮᱠᱚᱨᱰ",
        secureRecordsDesc: "ᱠᱞᱟᱣᱰ ᱨᱮ ᱢᱮᱰᱤᱠᱟᱞ ᱨᱤᱯᱚᱨᱛ ᱥᱩᱨᱠᱟᱹ ᱟᱹᱱᱤ ᱦᱩᱭ ᱢᱮ ᱟᱨ ᱧᱩᱛᱩᱢ ᱢᱮ।",
        smartQueue: "ᱥᱢᱟᱨᱛ ᱥᱟᱨᱤ ᱢᱮᱱᱟᱡᱟᱱ",
        smartQueueDesc: "ᱫᱟᱞᱟᱜ ᱠᱚ ᱨᱤᱭᱟᱞ-ᱴᱟᱭᱢ ᱴᱚᱠᱚᱱ ᱠᱷᱚᱱ ᱟᱡᱷᱟᱨ ᱟᱫᱮᱨ ᱧᱩᱛᱩᱢ",
        featuresHeader: "ᱟᱢᱟᱜ ᱛᱚᱞᱚᱢ ᱠᱷᱟᱸ",
        whyChoose: "ᱪᱮᱫ ᱥᱣᱟᱥᱛᱷᱟ-ᱢᱤᱛᱨᱟ ᱧᱮ?",
        profile: "ᱯᱨᱚᱯᱟᱭᱤᱞ",
        settings: "ᱥᱮᱴᱤᱝᱥ",
        logout: "ᱞᱚᱜ ᱟᱣᱴ",
        patients: "ᱫᱟᱞᱟᱜ",
        appointments: "ᱟᱯᱚᱭᱮᱱᱴᱢᱮᱱᱴ",
        reports: "ᱨᱤᱯᱚᱨᱴ",
        queue: "ᱥᱟᱨᱤ",
        search: "ᱥᱟᱨᱡᱟ",
        notifications: "ᱥᱩᱴᱤᱱ ᱞᱚᱢᱟ",
        home: "ᱦᱚᱢ"
    },
    bho: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डॉक्टर खोजीं",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर आ उनकर क्लिनिक देखें",
        doctorName: "डॉक्टर के नाम",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "शुरू करीं",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार में मरीज",
        avgWaitTime: "औसत इंतजार के समय",
        bookAppointment: "अपॉइंटमेंट बुक करीं",
        welcome: "स्वागत बा",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोकीं",
        triggerEmergency: "आपातकालीन मोड शुरू करीं",
        goodMorning: "सुप्रभात",
        upcoming: "आवे वाला",
        healthRecords: "स्वास्थ्य रिकॉर्ड",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक विजिट के बनाईं",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", आसान आ तनावमुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र मरीज कतार सँभालन से लेके AI इंतजार समय के अंदाजा तक सब काम देखेला।",
        aiWaitTime: "AI इंतजार समय अनुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बतावेला कि कतना देर रुकल जाई।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, ऐप ना त फोन कॉल से तुरंत बुक करीं।",
        secureRecords: "सुरक्षित स्वास्थ्य रिकॉर्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित ढंग से अपलोड करीं आ देखीं।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीज खातिर रियल-टाइम टोकन स्टेटस आ अनुमानित इंतजार समय।",
        featuresHeader: "रउरा खातिर बनेल फीचर",
        whyChoose: "काहे चुनीं स्वास्थ्य-मित्र?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजीं",
        notifications: "सूचनाएं",
        home: "घर"
    },
    raj: {
        appName: "स्वास्थ्य-मित्र",
        findDoctorsTitle: "डॉक्टर खोजो",
        findDoctorsSubtitle: "उपलब्ध डॉक्टर अणे ओनां रो क्लिनिक देखो",
        doctorName: "डॉक्टर रो नाम",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "शुरू करो",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार म रीझण",
        avgWaitTime: "औसत उडीक टेम",
        bookAppointment: "अपॉइंटमेंट बुक करो",
        welcome: "स्वागत है",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोको",
        triggerEmergency: "आपातकालीन मोड चालू करो",
        goodMorning: "राम राम सा",
        upcoming: "आवण आळा",
        healthRecords: "सेहत रिकॉर्ड",
        dietPlan: "खाण-पीण योजना",
        heroTitle: "क्लिनिक जावण ने बनाओ",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", आसान अणे तनावमुक्त",
        heroSubtitle: "स्वास्थ्य-मित्र मरीज कतार संभाळण सूं लैके AI उडीक टेम ने बतावण सूं सब काम करै।",
        aiWaitTime: "AI उडीक टेम अनुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बतावै के किण्णो समय इंतजारी करवी पडसी।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, एप अथवा फोन कॉल सूं झट बुक करो।",
        secureRecords: "सुरक्षित सेहत रिकॉर्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित रीत सूं अपलोड करो अणे देखो।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "रीजण माटे रियल-टाइम टोकन हाल अणे अंदाजित उडीक टेम।",
        featuresHeader: "थारा लेई बनायली सुविधाएं",
        whyChoose: "किणै स्वास्थ्य-मित्र चुनो?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "रीजण",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजो",
        notifications: "सूचना",
        home: "घर"
    },
    hne: {
        appName: "स्वास्थ्य-मितान",
        findDoctorsTitle: "डाक्टर खोजव",
        findDoctorsSubtitle: "उपलब्ध डाक्टर अऊ ओमन के क्लिनिक देखव",
        doctorName: "डाक्टर के नाम",
        doctorSpecialization: "विशेषता",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "सुरू करव",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार म मरीज",
        avgWaitTime: "औसत अगोरा बेरा",
        bookAppointment: "अपॉइंटमेंट बुक करव",
        welcome: "स्वागत हे",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोकव",
        triggerEmergency: "आपातकालीन मोड चालू करव",
        goodMorning: "जय जोहार",
        upcoming: "आगे आवत",
        healthRecords: "स्वास्थ्य रिकार्ड",
        dietPlan: "खान-पान योजना",
        heroTitle: "क्लिनिक जाथे ला आसान बनावव",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", गढ़बो आ तनावमुक्त",
        heroSubtitle: "स्वास्थ्य-मितान मरीज कतार सँभाले ले घेरी AI अगोरा बेरा के अनुमान लगाय ला सब काम करथे।",
        aiWaitTime: "AI अगोरा बेरा अनुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बताथें कति बेरा तक रुकना परी।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, एप नइ त फोन कॉल ले बुक करव।",
        secureRecords: "सुरक्षित स्वास्थ्य रिकार्ड",
        secureRecordsDesc: "क्लाउड म मेडिकल रिपोर्ट ला सुरक्षित रखव अऊ देखव।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीज बर रियल-टाइम टोकन स्थिति अऊ अनुमानित अगोरा बेरा।",
        featuresHeader: "तुम्हर बर बने सुविधा",
        whyChoose: "काबर चुनव स्वास्थ्य-मितान?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजव",
        notifications: "सूचना",
        home: "घर"
    },
    bgc: {
        appName: "स्वास्थ्य-मितर",
        findDoctorsTitle: "डाक्टर खोजौ",
        findDoctorsSubtitle: "उपलब्ध डाक्टर अउ उनकै क्लिनिक देखौ",
        doctorName: "डाक्टर का नांव",
        doctorSpecialization: "खासियत",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "सुरू करो",
        dashboard: "डैशबोर्ड",
        patientsQueue: "लाइन म मरीज",
        avgWaitTime: "औसत इंतजार टेम",
        bookAppointment: "अपॉइंटमेंट बुक करो",
        welcome: "स्वागत सै",
        emergencyMode: "एमरजेंसी मोड",
        stopEmergency: "एमरजेंसी मोड रोको",
        triggerEmergency: "एमरजेंसी मोड चालू करो",
        goodMorning: "राम राम",
        upcoming: "आण आला",
        healthRecords: "सेहत रिकार्ड",
        dietPlan: "खावन-पीवन योजना",
        heroTitle: "क्लिनिक जावन ने बनावौ",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", आसान अउ बिन तनाव",
        heroSubtitle: "स्वास्थ्य-मितर मरीज कतार सँभालै तै लइके AI इंतजार समा बतावै तक सब काम करै।",
        aiWaitTime: "AI इंतजार समय अनुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बतावै है किन्ना देर रुको परै।",
        easyBooking: "सहज बुकिंग",
        easyBookingDesc: "वेबसाइट, ऐप या फोन कॉल ते तुरत बुक करो।",
        secureRecords: "सुरक्षित सेहत रिकार्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित राखौ अउ देखौ।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीजां खातिर रियल-टाइम टोकन हाल अउ अनुमानित इंतजार समय।",
        featuresHeader: "तुम्हरें खातिर बनाय सुविधा",
        whyChoose: "काहे चुनौ स्वास्थ्य-मितर?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजौ",
        notifications: "सूचनाएं",
        home: "घर"
    },
    mag: {
        appName: "स्वास्थ्य-मितर",
        findDoctorsTitle: "डाक्टर खोजीं",
        findDoctorsSubtitle: "उपलब्ध डाक्टर आ उनकर क्लिनिक देखीं",
        doctorName: "डाक्टर के नाव",
        doctorSpecialization: "खासियत",
        doctorClinic: "क्लिनिक/अस्पताल",
        login: "लॉग इन",
        register: "रजिस्टर",
        getStarted: "शुरू करीं",
        dashboard: "डैशबोर्ड",
        patientsQueue: "कतार में मरीज",
        avgWaitTime: "औसत इंतजार बर समय",
        bookAppointment: "अपॉइंटमेंट बुक करीं",
        welcome: "स्वागत ह",
        emergencyMode: "आपातकालीन मोड",
        stopEmergency: "आपातकालीन मोड रोकू",
        triggerEmergency: "आपातकालीन मोड चालू करीं",
        goodMorning: "सुप्रभात",
        upcoming: "आवे वाला",
        healthRecords: "स्वास्थ्य रिकॉर्ड",
        dietPlan: "आहार योजना",
        heroTitle: "क्लिनिक जाए के बनाईं",
        heroTitleHighlight: "स्मार्ट",
        heroTitleEnd: ", आसान आ बिन तनाव",
        heroSubtitle: "स्वास्थ्य-मितर मरीज कतार सँभाले से ले के AI इंतजार समय के अन्दाजा तक सब काम देखे ला।",
        aiWaitTime: "AI इंतजार समय अनुमान",
        aiWaitDesc: "मशीन लर्निंग मॉडल बतावेला कि कतना देर रुकल जा सकेला।",
        easyBooking: "आसान बुकिंग",
        easyBookingDesc: "वेबसाइट, ऐप ना त फोन कॉल से तुरते बुक करीं।",
        secureRecords: "सुरक्षित स्वास्थ्य रिकॉर्ड",
        secureRecordsDesc: "क्लाउड पर मेडिकल रिपोर्ट सुरक्षित राखीं आ देखीं।",
        smartQueue: "स्मार्ट कतार प्रबंधन",
        smartQueueDesc: "मरीज खातिर रियल-टाइम टोकन हाल आ अनुमानित इंतजार समय।",
        featuresHeader: "तोहरा खातिर बनावल फीचर",
        whyChoose: "काहे चुनब स्वास्थ्य-मितर?",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉग आउट",
        patients: "मरीज",
        appointments: "अपॉइंटमेंट",
        reports: "रिपोर्ट",
        queue: "कतार",
        search: "खोजीं",
        notifications: "सूचनाएं",
        home: "घर"
    },
    tcy: {
        appName: "ಸ್ವಾಸ್ಥ್ಯ-ಮಿತ್ರ",
        findDoctorsTitle: "ಡಾಕ್ಟರ್ ಕಂಡ್ ತಿಕ್ಕೋ",
        findDoctorsSubtitle: "ಸಿಗ್ಪುನ ಡಾಕ್ಟರ್‌ಲು ಮತ್ ಅವರ್ ಕ್ಲಿನಿಕ್ ನೋಡಿಯೆ",
        doctorName: "ಡಾಕ್ಟರ್ ಪುದರ್",
        doctorSpecialization: "ವಿಶೇಷತೆ",
        doctorClinic: "ಕ್ಲಿನಿಕ್/ಆಸ್ಪತ್ರೆ",
        login: "ಲಾಗಿನ್",
        register: "ನೋಂದಣಿ",
        getStarted: "ಆರಂಭ ಮಲ್ಪು",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        patientsQueue: "ಸರತಿಡ್ ರೋಗಿಲು",
        avgWaitTime: "ಸರಾಸರಿ ಕಾಯುವ ಪೊರ್ತು",
        bookAppointment: "ಅಪಾಯಿಂಟ್ಮೆಂಟ್ ಬುಕ್ ಮಲ್ಪು",
        welcome: "ಸ್ವಾಗತ",
        emergencyMode: "ತುರ್ತು ಸ್ಥಿತಿ",
        stopEmergency: "ತುರ್ತು ಸ್ಥಿತಿ ನಿಲ್ಲ್ಸು",
        triggerEmergency: "ತುರ್ತು ಸ್ಥಿತಿ ಸುರು ಮಲ್ಪು",
        goodMorning: "ಎಡ್ಡೆ ಕಾಂಡೆ",
        upcoming: "ಬರ್ಪುನ",
        healthRecords: "ಆರೋಗ್ಯ ದಾಖಲೆಲು",
        dietPlan: "ಆಹಾರ ಯೋಜನೆ",
        heroTitle: "ಕ್ಲಿನಿಕ್ ಭೇಟಿ ಸುಲಭ ಮಲ್ಪು",
        heroTitleHighlight: "ಸ್ಮಾರ್ಟ್",
        heroTitleEnd: ", ನಯ ಮತ್ ತಲೆಬೆತ್ತಲ್ದ್ ಇಲ್ದೆ",
        heroSubtitle: "ಸ್ವಾಸ್ಥ್ಯ-ಮಿತ್ರ ರೋಗಿ ಸರತಿ ನಿಭಾಯ್ಲೆಂದ್ AI ಕಾಯುವ ಪೊರ್ತು ಅಂದಾಜ್ ತನಕಲ್ಲ ಒಟ್ಟು ಸಹಾಯ ಮಲ್ಪುಂಡು.",
        aiWaitTime: "AI ಕಾಯುವ ಪೊರ್ತು ಅಂದಾಜ್",
        aiWaitDesc: "ಮಶಿನ್ ಲರ್ನಿಂಗ್ ಮೋಡಲ್ ನಿಂಗ್ಗು ಎಷ್ಟ್ ಕಾಲ ಕಾಯ್ಲೆಂದ್ ತೋರ್ತು।",
        easyBooking: "ಸುಲಭ ಬುಕಿಂಗ್",
        easyBookingDesc: "ವೇಬ್ಸೈಟ್, ಆಪ್ ಅಥ್ವಾ ಫೋನ್ ಕಾಲ್ ದ್ವಾರ ಬುಕ್ ಮಲ್ಪು।",
        secureRecords: "ಸುರಕ್ಷಿತ ಆರೋಗ್ಯ ದಾಖಲೆ",
        secureRecordsDesc: "ಕ್ಲೌಡ್ ದಲ್ಲೆ ವೈದ್ಯಕೀಯ ವರದಿ ಸುರಕ್ಷಿತ ಆಯ್ದ್ ಉಳ್ಸಿ ನೋಡಿಯೆ।",
        smartQueue: "ಸ್ಮಾರ್ಟ್ ಸರತಿ ನಿರ್ವಹಣೆ",
        smartQueueDesc: "ರೋಗಿಗ್ ರಿಯಲ್-ಟೈಮ್ ಟೋಕನ್ ಸ್ಥಿತಿ ಮತ್ ಅಂದಾಜಿನ ಕಾಯುವ ಪೊರ್ತು।",
        featuresHeader: "ನಿಮ್ಕ್ ತಕ್ಕದು ಆಯ್ದ್ ವೈಶಿಷ್ಟ್ಯ",
        whyChoose: "ಯಾಕ್ ಸ್ವಾಸ್ಥ್ಯ-ಮಿತ್ರ ಆಯ್ಕೆ ಮಲ್ಪೆ?",
        profile: "ಪ್ರೊಫೈಲ್",
        settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
        logout: "ಲಾಗ್ ಔಟ್",
        patients: "ರೋಗಿ",
        appointments: "ಅಪಾಯಿಂಟ್ಮೆಂಟ್",
        reports: "ರಿಪೋರ್ಟ್",
        queue: "ಸರತಿ",
        search: "ಹುಡುಕು",
        notifications: "ಸೂಚನೆಲು",
        home: "ಗುಡಿ"
    },
    kha: {
        appName: "Swasthya-Mitra",
        findDoctorsTitle: "Sheh ïa ki Doctor",
        findDoctorsSubtitle: "Peit ïa kiba don bad ki jaka sumar jong ki",
        doctorName: "Ka kyrteng Doctor",
        doctorSpecialization: "Ka Specialization",
        doctorClinic: "Clinic/Hospital",
        login: "Login",
        register: "Register",
        getStarted: "Sdang",
        dashboard: "Dashboard",
        patientsQueue: "Ki nongpang ha ka line",
        avgWaitTime: "Por ap jaka",
        bookAppointment: "Buk ïa ka Appointment",
        welcome: "Khublei",
        emergencyMode: "Emergency Mode",
        stopEmergency: "Pynsangeh Emergency",
        triggerEmergency: "Pyniaid Emergency",
        goodMorning: "Khublei step",
        upcoming: "Ki ban wan",
        healthRecords: "Ka jingthoh koit jingkhiah",
        dietPlan: "Ka rukom bam",
        heroTitle: "Pynsuk ïa ka jingleit sha clinic",
        heroTitleHighlight: "Smarter",
        heroTitleEnd: ", suk bad khlem jingsngewkhia",
        heroSubtitle: "Swasthya-Mitra ka bat ïa ki kam naduh ka jingpynbeit ïa ki lain haduh ka jingmaham por ap da ka AI, ka long kum u nongiarap ba khlem poi pyrthei.",
        aiWaitTime: "AI jingmaham por ap",
        aiWaitDesc: "Ki model machine learning ki kdew katno por ngin ap.",
        easyBooking: "Buk kaba suk",
        easyBookingDesc: "Buk lyngba ka website, app ne da ka phone call.",
        secureRecords: "Ka jingthoh koit jingkhiah kaba shngain",
        secureRecordsDesc: "Upload bad peit ïa ki report da kaba shngain ha ka cloud.",
        smartQueue: "Ka jingpyniaid lain ba smat",
        smartQueueDesc: "Ka hukum token ha ka por tynrai bad ka por ap ba la bishar.",
        featuresHeader: "Ki rukom treikam ba la thaw na bynta phi",
        whyChoose: "Balei ban jied ïa Swasthya-Mitra?",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        patients: "Ki nongpang",
        appointments: "Ki appointment",
        reports: "Ki report",
        queue: "Line",
        search: "Sheh",
        notifications: "Ki jingtip",
        home: "Ing"
    },
    grt: {
        appName: "Swasthya-Mitra",
        findDoctorsTitle: "Doctor Isua",
        findDoctorsSubtitle: "Lakkini doctor aro klinikrang nibo",
        doctorName: "Doctor minggipa",
        doctorSpecialization: "Dakgipa skian",
        doctorClinic: "Clinic/Hospital",
        login: "Login",
        register: "Register",
        getStarted: "Rakkie ra'na",
        dashboard: "Dashboard",
        patientsQueue: "Line-ni cholko a·gilsak",
        avgWaitTime: "Sengsang kusi somoi",
        bookAppointment: "Appointment book ka·bo",
        welcome: "Rimchakso",
        emergencyMode: "Emergency Mode",
        stopEmergency: "Emergency songjinbo",
        triggerEmergency: "Emergency dondikbo",
        goodMorning: "Pringnam",
        upcoming: "Chanchia ong·gen",
        healthRecords: "An·seng baljokatgipa",
        dietPlan: "Cha·ani bewal",
        heroTitle: "Clinic rang·ja chakatbo",
        heroTitleHighlight: "Smarte",
        heroTitleEnd: ", skanggipa aro ma·sigipa",
        heroSubtitle: "Swasthya-Mitra patient queue niboranirangko aro AI wait time nikna bimungka kamrangko dakgipa digital saksachini ong·a.",
        aiWaitTime: "AI wait time nikna",
        aiWaitDesc: "Machine learning modelrang nibo na·a maikai somoi ong·gen ine.",
        easyBooking: "Sangsak booking",
        easyBookingDesc: "Website, app aro phone call cholko skanggipa minggiparang buko.",
        secureRecords: "Seksak an·seng baljokatgipa",
        secureRecordsDesc: "Cloud chong·a medical reportrangko seksak ong·bo aro nikbo.",
        smartQueue: "Smart queue nokgipa",
        smartQueueDesc: "Rogiparangna real-time token gimin aro sengsang kusi somoi.",
        featuresHeader: "Na·a na·a gimin ong·gipa kam",
        whyChoose: "Maikai Swasthya-Mitra jekode?",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        patients: "Rogi",
        appointments: "Appointment",
        reports: "Report",
        queue: "Line",
        search: "Nibo",
        notifications: "Notification",
        home: "Nok"
    },
    lus: {
        appName: "Swasthya-Mitra",
        findDoctorsTitle: "Doktawr hmu rawh",
        findDoctorsSubtitle: "Inthlahna doktawr leh an clinic thu chu en rawh",
        doctorName: "Doktawr hming",
        doctorSpecialization: "Thawk dan pawimawh",
        doctorClinic: "Clinic/Hospital",
        login: "Lut rawh",
        register: "Register rawh",
        getStarted: "Hlawhtling rawh",
        dashboard: "Dashboard",
        patientsQueue: "Damlo inthlahna",
        avgWaitTime: "Nghah hun chawlhna",
        bookAppointment: "Appointment siam rawh",
        welcome: "Chibai",
        emergencyMode: "Emergency Mode",
        stopEmergency: "Emergency ti tawp rawh",
        triggerEmergency: "Emergency tanpui rawh",
        goodMorning: "Chibai le",
        upcoming: "Lo thleng tura",
        healthRecords: "Hriselna chanchin",
        dietPlan: "Ei tura duan",
        heroTitle: "Clinic kalna chu",
        heroTitleHighlight: "hmante",
        heroTitleEnd: ", remchang leh rilru tha",
        heroSubtitle: "Swasthya-Mitra chuan damlo inthlahna siamtu leh AI nghah hun inziahna chu a tuipui vek a nia, vawiin damdawi'n i hruai rem tak a ni.",
        aiWaitTime: "AI nghah hun hrilhfiahna",
        aiWaitDesc: "Machine learning model ten eng emaw hun nge i nghah ang an hrilh che.",
        easyBooking: "Sual leh ngai lo booking",
        easyBookingDesc: "Website, app emaw phone call hmangin khuar eng emaw book rawh.",
        secureRecords: "Hriselna thupek siamtham",
        secureRecordsDesc: "Cloud-ah medical report te a Thianghlim takin upload leh en rawh.",
        smartQueue: "Smart queue siamtu",
        smartQueueDesc: "Damlo tan real-time token hriatna leh nghah hun thlirna",
        featuresHeader: "I tanin siam a ni",
        whyChoose: "Engati nge i thlang a nia Swasthya-Mitra?",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        patients: "Damlo",
        appointments: "Appointment",
        reports: "Report",
        queue: "Queue",
        search: "Zawn",
        notifications: "Thutiam",
        home: "In"
    },
    trp: {
        appName: "Swasthya-Mitra",
        findDoctorsTitle: "Doktor borok ni",
        findDoctorsSubtitle: "Lopani doktor aro klinik ongmani okhai",
        doctorName: "Doktor mung",
        doctorSpecialization: "Specialization",
        doctorClinic: "Clinic/Hospital",
        login: "Login",
        register: "Register",
        getStarted: "Surulai",
        dashboard: "Dashboard",
        patientsQueue: "Line-ani rogi",
        avgWaitTime: "Ginizi ba somoi",
        bookAppointment: "Appointment book khwlai",
        welcome: "Khulumkha",
        emergencyMode: "Emergency mode",
        stopEmergency: "Emergency mode thungdi",
        triggerEmergency: "Emergency mode chamthai",
        goodMorning: "Khulumkha pai",
        upcoming: "Pai nai",
        healthRecords: "Hamkwrai record",
        dietPlan: "Chamnok plan",
        heroTitle: "Clinic dongmani ka",
        heroTitleHighlight: "smarte",
        heroTitleEnd: ", sahaj aro khumthai",
        heroSubtitle: "Swasthya-Mitra patient line chamani o, AI wait time gwswla okrang ni tahar hamjakba digital doksa.",
        aiWaitTime: "AI wait somoi gwswla",
        aiWaitDesc: "Machine learning model nai somoi gwswla hamjakba.",
        easyBooking: "Sahaj booking",
        easyBookingDesc: "Website, app ni phone call hanthai buk khwlai.",
        secureRecords: "Surokha hamkwrai record",
        secureRecordsDesc: "Cloud-ani medical report surakha ongmani aro enmani.",
        smartQueue: "Smart queue chamani",
        smartQueueDesc: "Rogi borokni real-time token gwswla aro giniz somoi.",
        featuresHeader: "Nokor ni singdwng",
        whyChoose: "Haini Swasthya-Mitra borok?",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        patients: "Rogi",
        appointments: "Appointment",
        reports: "Report",
        queue: "Queue",
        search: "Khunjak",
        notifications: "Notification",
        home: "Nok"
    }
};

/**
 * Supplies translation helpers and language-specific assets to the app tree.
 * Wraps components so they can read/update the active locale without prop drilling.
 */
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    // Returns translated string or the key itself when a copy line is missing
    const t = (key) => {
        return translations[language][key] || key;
    };

    // Selects the appropriate brand mark for the current locale
    const getLogo = () => {
        return logoMap[language] || logoMap.en;
    };

    // Simple round-robin language switcher used by admin navbar
    const toggleLanguage = () => {
        const languages = Object.keys(translations);
        const currentIndex = languages.indexOf(language);
        const nextIndex = (currentIndex + 1) % languages.length;
        setLanguage(languages[nextIndex]);
    };

    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t, getLogo }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
